### PR TITLE
Add sarima

### PR DESCRIPTION
**Pull request by shubhamitc**
* Sarima code addition

### CODE REVIEW

**Comment by shubhamitc** [comment]
what are the linting/testing guidelines for python?

**Comment by jthomperoo** [comment]
Hello, thanks very much, so for the linting rules you can run:
`make lint`
You can check out some of the make commands here: https://github.com/jthomperoo/predictive-horizontal-pod-autoscaler#commands
And the contributing guide here: https://github.com/jthomperoo/predictive-horizontal-pod-autoscaler/blob/master/CONTRIBUTING.md

**Comment by shubhamitc** [comment]
@jthomperoo saw your comments a little late. Now linting issues are passing.

**Comment by jthomperoo** [comment]
Hey, so the core of this looks good, using ARIMA, there are some things I'm not entirely sure why they are in:

- Why are there Flask endpoints? The algorithms in these folders are intended to be run from a shell command.
- How is the model handled here, when would training happen as part of the autoscaling lifecycle?
- How does the test work? It seems to generate random data?
- This would have to be integrated in a similar way to the linear regression algorithm with the Golang autoscaler logic otherwise this wont work.

Thanks!

**Comment by shubhamitc** [comment]
Let’s convert this into shell executable, I will refer to linear regression model. 
Like other models Sarima requires a large data set to train with and generate a model file. With predict , we can ask for new predictions and update the model as well. Sarima requires minimum 1 day of old data set. 
Yes; test correctly generates only training data set.

**Comment by shubhamitc** [comment]
Hi, I have converted the code to look something like the below, with considerations that SARIMA needs a large dataset for training. Hence adding 2 methods `train` and predict as an action type. Let me know if this seems to fit the use case that you have. I will write the test cases post-confirmation. 


```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Sarima algorithm for prediction.
Using the same dataset as linear_regression model.
Removing flask code in favour of subprocess.
Takes in list of stored evaluations and the look ahead value:
{
"lookAhead": 3,
"action": "train|predict",
"evaluations": [
    {
        "id": 0,
        "created": "2020-02-01T00:55:33Z",
        "val": {
            "targetReplicas": 3
        }
    },
    {
        "id": 1,
        "created": "2020-02-01T00:56:33Z",
        "val": {
            "targetReplicas": 2
        }
    }
]
}
"""
from json import JSONEncoder
import json
import sys
import os
import pickle
import numpy
import pandas as pd
from pmdarima.arima import auto_arima


# app = Flask(__name__)
MODEL_LOCATION = '/tmp/arima.pkl'
ACTION='action'
INDEX='created'
TRAIN='train'
PRDICT='predict'
LOOKAHEAD='lookAhead'


class NumpyArrayEncoder(JSONEncoder):
    '''
    NumpyArraryEncoder class
    '''

    def default(self, o):
        '''
        obj: ndarray to json
        '''
        if isinstance(o, numpy.ndarray):
            return o.tolist()
        return JSONEncoder.default(self, o)


def train(request_json):
    '''
    Post method to return default json object with 200OK
    '''
    data = pd.DataFrame.from_dict(request_json, orient=INDEX
                                  ).T.set_index(INDEX)
    stepwise_model = auto_arima(
        data,
        start_p=1,
        start_q=1,
        max_p=3,
        max_q=3,
        m=12,
        start_P=0,
        seasonal=True,
        d=1,
        D=1,
        trace=True,
        error_action='ignore',
        suppress_warnings=True,
        stepwise=True,
        )
    # print(stepwise_model.aic())
    # print(stepwise_model.summary())

    # Serialize with Pickle

    with open('/tmp/arima.pkl', 'wb') as pkl:
        pickle.dump(stepwise_model, pkl)

    return json.dumps('{"success":1}')


def load_pred(location):
    '''
    Load prediction from location
    location: default path to load prediction from
    Returns: Picket object
    '''
    f_d = open(location, 'rb')
    return pickle.load(f_d)


def update_model(location, data):
    '''
    Update model with latest data
    location: Location of model to load from
    data: new data to update the model with
    Returns: pickled model
    '''
    model = load_pred(location)
    model.update(data)
    with open(location, 'wb') as pkl:
        pickle.dump(model, pkl)
    return model


def predict(request_json,n_periods):
    '''
    Load prediction and update them with existing model
    Returns: Jsonify data
    '''
    data = pd.DataFrame.from_dict(request_json, orient=INDEX
                                  ).T.set_index(INDEX)
    model = update_model(MODEL_LOCATION, data)
    (prediction, new_conf_int) = model.predict(n_periods=n_periods, return_conf_int=True)
    # print(new_conf_int)
    return json.dumps(prediction, cls=NumpyArrayEncoder)

if __name__ == '__main__':
    stdin = sys.stdin.read()
    if stdin is not None:
        try:
            input_json = json.loads(stdin)
            action = input_json.get(ACTION,None)
            if action == TRAIN:
                print(train(input_json))
            elif action == PREDICT:
                # Setting 3 as default if lookahead is not present
                print(predict(input_json, input_json.get(LOOKAHEAD,3)))
        except JSONDecodeError as ex:
            print("Invalid JSON provided: {0}, exiting".format(str(ex)), file=sys.stderr)
            sys.exit(1)
        except Exception as ex:
            print("Exception while processing SARIMA algorithm", ex)
            sys.exit(1)
    else:
        print("No standard input provided to SARIMA algorithm, exiting", file=sys.stderr)
        sys.exit(1)


```

**Comment by jthomperoo** [comment]
Sorry it took me so long to respond to this; just been swamped and very busy across multiple projects! This looks great, I'm going to try to finalise up the conversion from Golang to Python, then I can merge in your changes and integrate them with the Golang codebase!

**Pull request closed without merging**
